# Generated by Django 4.2.7 on 2024-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=30)),
                ('username', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(blank=True, max_length=30)),
                ('academy', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('age', models.IntegerField(blank=True)),
                ('role', models.CharField(max_length=30)),
                ('stamina', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('skill', models.IntegerField()),
                ('total', models.IntegerField()),
                ('create_user', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
