# Generated by Django 4.2.7 on 2024-07-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piratemembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('academy', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('Men', 'Men'), ('Female', 'Female'), ('LGBTQ+', 'LGBTQ+')], max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
