# Generated by Django 5.0.7 on 2024-07-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piratemembers', '0002_user_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_used',
            field=models.BooleanField(default=False),
        ),
    ]
