# Generated by Django 5.0.7 on 2024-07-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piratemembers', '0003_user_random_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='random_used',
        ),
    ]
