# Generated by Django 5.0.7 on 2024-07-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piratemembers', '0004_remove_user_random_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='heal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='random_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stamina',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
